### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref#105]
Since Symfony 4.2 was released the phpstan build is broken with these errors:

> Parameter #1 $command of class Symfony\Component\Process\Process constructor expects array, string given.

See https://travis-ci.com/mnapoli/bref/jobs/162831081

Since I'm focused on the benchmarks and v0.3 that would be awesome if someone were to send a pull request to fix this. While I don't want to say this is easy I have to say this shouldn't be extra hard: the string parameter should be changed to an array (split each argument). A good way to get started contributing ;)

**Comment by MickaelTH** [comment]
I was working on that. Fixing phpstan is easy but other issues are appearing during phpunit.

I will make a PR for the fix in phpstan but build will still fail because of phpunit issues and are pretty weird ... at least for me for now.

**Comment by mnapoli** [comment]
:+1: ok I wasn't expecting that, thanks anything that improves the situation is good.

**Comment by MickaelTH** [comment]
I only focused on phpstan PR #108 

I also add the phpunit errors if relevant for another issue into the PR.
