### ISSUE TITLE
The process "serverless deploy" exceeded the timeout of 60 seconds.

### ISSUE THREAD

**Issue by lulco** [mnapoli/bref#12]
I have downloaded new version of framework and I get this error in last step of deploy:

```
vendor/bin/bref deploy
Uploading the lambda
 7/8 [░░░░░░░░░░░░░░░░░░░░░░░░    ]  1 sec

In Process.php line 1154:

  The process "serverless deploy" exceeded the timeout of 60 seconds.


deploy
```

It seems application is deployed but I am not sure what will missing.

**Comment by mnapoli** [comment]
Ohh I just moved today to using the Symfony Process component and I think it has a timeout of 60 seconds by default (https://symfony.com/doc/current/components/process.html#process-timeout).

I'll change that to remove the timeout hold on!

**Comment by mnapoli** [comment]
`0.2.10` is released with a fix.

**Comment by lulco** [comment]
thx, now everything is OK
