### ISSUE TITLE
Support CakePHP console commands

### ISSUE THREAD

**Issue by swiffer** [mnapoli/bref#133]
https://book.cakephp.org/3.0/en/console-and-shells/commands.html

I'm currently using CakePHP console commands for some tasks scheduled via cron. Excited to try running these on AWS Lambda but missing an example on how to wrap / run these within bref.

Looks like these are not based on Symfony Console. Would you mind passing an example or isn't it possible at all getting these up and running currently?

**Comment by mnapoli** [comment]
Right, with the current version of Bref there is only support for Symfony Console.

With the next version that is being worked upon any framework will be supported. [Here](https://github.com/mnapoli/bref/blob/7c0167804902c02e9ec9d9f40d2b92e7e10a3f1a/docs/runtimes/console.md) is a preview of the future documentation.

Follow #113 if you want to be alerted about v0.3.

**Comment by mnapoli** [comment]
Please give a try to v0.3 (which is not released yet, see #113). The documentation for console applications is here: https://bref.sh/docs/runtimes/console.html

All frameworks should be supported now.
