### ISSUE TITLE
Laravel documentation for 0.3

### ISSUE THREAD

**Issue by pmayet** [mnapoli/bref#136]
@mnapoli You indicate this command `vendor/bin/bref init` but in my opinion it's no longer necessary, especially since "init" is in error because of the absence of serverless.

`[ERROR] The serverless command is not installed.
         Please follow the instructions on https://github.com/mnapoli/bref#setup`

**Comment by mnapoli** [comment]
I think this is because you are using the 0.2 version?

**Comment by agueroveraalvaro** [comment]
Update to `"mnapoli/bref": "0.2.9",` and works fine!
