### ISSUE TITLE
Region support in 0.3

### ISSUE THREAD

**Issue by gregmsanderson** [mnapoli/bref#152]
I see that in the new docs, for 0.3, https://bref.sh/docs/runtimes/ lists only _us-east-2_ and says that runtime region needs to match where the application is.

However on https://bref.sh/docs/installation.html it says while _us-east-1_ is the default, you can pick another region, like _eu-west-1_ to host the application closer to visitors ...

If the runtime is only available in us-east-2, does that mean the application needs to be there too? Or can that runtime be moved to e.g. eu-west-1 so that everything can be hosted there (aplication, runtime, DB etc)? Or can the runtime be in a different region?

Thanks!

**Comment by mnapoli** [comment]
> If the runtime is only available in us-east-2, does that mean the application needs to be there too?

Yes.

However we intend to provide the layers in every region. This is in the works in #150 ;)

**Comment by gregmsanderson** [comment]
Ooh nice. Great work. I'd prefer to use eu-west-1/2.

**Comment by mnapoli** [comment]
This is done, see https://github.com/mnapoli/bref/issues/116#issuecomment-454165715
