### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by gregmsanderson** [mnapoli/bref#156]
I did a quick run through, making a sample HTTP application which basically just consists of an index.php, and running the deploy command:

sam package --output-template-file .stack.yaml --s3-bucket _MY-NAME_
sam deploy --template-file _MY-PATH_ --capabilities CAPABILITY_IAM --stack-name _MY-NAME_

The _package_ seemed to work and indeed a file ends up in the specified S3 bucket. But then it failed at the point of creating the stack. Checking the logs for why, as it suggests, shows this as the _likely_ issue:

```
...
"ResourceStatus": "CREATE_FAILED",
"ResourceType": "AWS::Lambda::Function",
"Timestamp": "2019-01-11T20:48:16.278Z",
"ResourceStatusReason": "User: arn:aws:iam::MY-NUMBER:user/MY-NAME is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-2:416566615250:layer:php-72-fpm:3 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException
...
```

It seems my user does not have access to the layer. Which I guess makes sense, as that's not owned by me. Do I need to add extra permissions at my end to my IAM user to get access to it? Or do you have to do something at your end to make it more permissive?

I did initially wonder if it was a region issue since my bucket is in eu-west-1 and the layer in us-east-2 but it sounds more like a IAM thing ... ? Hmm.

Thanks!

**Comment by gregmsanderson** [comment]
... oh, and further to the previous question about supported regions, do I currently need to make the bucket in _us-east-2_ and also add the flag _--region us-east-2_ to the deploy command? Since that is where the layer currently is?

I get going forward you'll be adding layers in other regions, but for now does that have to be done? I'm trying to wrap my brain around this, sorry!

**Comment by mnapoli** [comment]
I'm not sure exactly why you are getting this, but here is what I noted:

- you must deploy everything in the same region (us-east-2 for now), everything ;)
- the latest version of the layer is `4`, maybe try that too?

**Comment by gregmsanderson** [comment]
It works! Genius. Thank you.

I don't know what exactly fixed it, but a combination of changing the layer to version to 4 in the yaml, making a brand new bucket in us-east-2, and adding the _--region us-east-2_ to the deploy command resulted in a successful stack creation :) I got hello world. Awesome.

This could really be great if it can be stable for production usage.

**Comment by mnapoli** [comment]
Yes as we are still in development this is not really practical. Once it's available everywhere it should be easier ^^

**Comment by jpike88** [comment]
This isn't clear enough in the cli while using it. The documentation site states:

```
If you are a first time user, using the us-east-1 region (the default region) is highly recommended for the first projects. It simplifies commands and avoids a lot of mistakes when discovering AWS.
```

This is a dealbreaker for many people, especially if the lambda is dealing with sizable payloads. I put a lot of effort into this to find that the only supported configuration of this is going to whack me hard with unnecessary costs.

Is there any documented way to move the lambda to another region? If so, why not?

**Comment by mnapoli** [comment]
@jpike88 I'm sorry but maybe I'm missing something. It is absolutely possible to use Bref in all regions.

This documentation quote is just a recommendation for people getting started with AWS, so that they have less trouble with regions (it's easy to make a mistake with those).

Maybe we should make that sentence more clear? Do you have a suggestion? I really want future people to not be confused like you may have been ^^

**Comment by jpike88** [comment]
My bad. I was under the impression that didn’t work.

There no clear instruction for firing up my lambda elsewhere. Only stuff related to this region configuration item, which I now understand is necessities the same, and setting it us-east-1 Is just basic setup stuff.

What do I need to do to have my lambda running in ap-southeast-2? There doesn’t seem to be any clear instructions about it.

**Comment by jpike88** [comment]
I should add, I tried setting that thing to us-east-1 but got the same error message described in this issue. My knowledge of cloud formation is limited and I want to keep it that way if possible

**Comment by mnapoli** [comment]
@jpike88 When you do `vendor/bin/bref init` you get this in `serverless.yml`:

```yaml
service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided

# ...
```

Change the `region` to your region.

Could we continue the discussion in a separate issue though? That way we don't ping users involved in the previous discussion from last year.

**Comment by jpike88** [comment]
I’ll continue to experiment and if still failing I’ll make one within the next couple of hours, thanks
