### ISSUE TITLE
awscli is a prerequirement over aws-sam-cli [docs confusing?]

### ISSUE THREAD

**Issue by swiffer** [mnapoli/bref#163]
aws-cli is a prerequirement of sam - could be noted in the new docs instead of making it optional?

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html

**Comment by mnapoli** [comment]
Good catch! I wasn't sure about that and I didn't document it, turns out I was wrong.

So yep we need to update the docs to explain this.

**Comment by mnapoli** [comment]
Closed by #165
