### ISSUE TITLE
Extend Docs // CakePHP guide for 0.3

### ISSUE THREAD

**Issue by swiffer** [mnapoli/bref#167]
I would be willing to contribute a guide documenting the specifics of running CakePHP as application on top of the phpfpm layer.

Additionally I think it would be super helpful to extend the automatic deployment section by providing a proper example of a gitlab ci pipeline e.g.

Third a best practice guide of how your repo should be structured (#134) would be super helpful.

**Comment by bubba-h57** [comment]
CakePHP guide would be welcome! Just provide a PR against the https://github.com/mnapoli/bref/tree/0.3/docs/frameworks directory with a `cake.md`?

**Comment by mnapoli** [comment]
@swiffer what specific steps did you have to take in order to make CakePHP run?

**Comment by swiffer** [comment]
conditionally modified some paths when env var `AWS_LAMBDA_FUNCTION_NAME` is present.

Would add sections for Database Access and storing logs on cloudwatch by adding and configuring https://github.com/awallef/cakephp-cw-log

**Comment by mnapoli** [comment]
Honestly I'm not sure a separate guide for CakePHP makes sense, I think we should keep the documentation as simple as possible and I wouldn't categorize Cake as a major PHP framework like Laravel or Symfony at the moment.

Maybe we could have a guide `Other frameworks` where we group things in there. In the meantime for v0.3 I believe we should focus on the major players and keep things as simple as possible.

Let's revisit later!
