### ISSUE TITLE
Split bref into multiple packages

### ISSUE THREAD

**Issue by sandrokeil** [mnapoli/bref#172]
I think it is useful to split bref at least into two packages:

- `bref`: contains only *src* folder (PHP classes to handle Lambda requests)
- `bref-cli`: contains Lambda template(s) and CLI (testing, code generation, deploy) stuff

## bref
Should suggest Composer dependencies instead of require all things e.g. for CLI (`LambdaRuntime`) I don't need `HOA`. Maybe this can done automatically on `bref init`.

## bref-cli
Can be distributed as phar and does not add additional hidden dependencies to the project. This would also resolve version conflicts depending on used packages.

Additional packages and further splitting could be:
- `bref-http`: PSR 7, PHP-FPM stuff
- `bref-runtime`: Contains the runtimes

This should be considered before 0.3 release or a BC break is used in further versions.

**Comment by mnapoli** [comment]
Thanks for the suggestion, I intend to do that once I know I can manage the additional overhead of the split.

At the moment this would take too much work that I wouldn't be able to put into more useful things for the project.

Let's revisit later!
