### ISSUE TITLE
Include and enable the zip extension

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref#173]
Issue forked from #143 

At the moment the `zlib` extension is installed and enabled but not the `zip` extension.

Explanations of the difference by @bubba-h57:

> The [zlib](http://php.net/manual/en/book.zlib.php) and the [zip](http://php.net/manual/en/book.zip.php) extensions are different, but the differences are subtle.
>
> At a high level, think of **zlib** as handling `gzip` files and **zip** handling `zip` files. 
>
> It can get confusing because you will run across documentation that purports **zlib** can handle `zip` files. **zlib** can indeed handle `zip` files if, and only if, the `zip` file uses `deflate` compression.
>
> However, while **zlib** has stuck to the `deflate` algorithm, `zip` files can support a much wider range of compression algorithms, even mixing compression in the same `zip` file, and it is not reliable to expect **zlib** to open a `zip` file.

Another issue is that `zlib` does not include the `ZipArchive` class.

@bubba-h57 if `zip` has advantages over `zlib` are there any reason we shouldn't use zip instead?

**Comment by pmayet** [comment]
Thank's, I have build my own layer with extension `zip`, It works !

**Comment by mnapoli** [comment]
Right, I still think for the project if there are no downsides we should probably install zip instead?

**Comment by bubba-h57** [comment]
I know a lot of libraries bind to **zlib**, so we have to build it anyway. I believe pecl requires`zlib`? I reckon the easiest thing is to simply include the zip extension along with it.

**Comment by mnapoli** [comment]
OK thanks for the update, let's include both then 💪

**Comment by mnapoli** [comment]
@fredericgboutin-yapla note that this is a very old issue, I'm not 100% sure it's still accurate with the current Bref versions (I don't remember right now)

But if it is, happy to merge a PR indeed!

Also I'm interested to learn more how you use Bref at your company, feel free to send me an email :) (en français 👍)

**Comment by aromka** [comment]
It would be good to have this included in the docs since there is no information on this available, and it's not part of extended extensions, but it looks like libzip is indeed included in the build - https://github.com/brefphp/aws-lambda-layers/blob/main/php-84/Dockerfile#L293

**Comment by mnapoli** [comment]
@aromka it's there: https://bref.sh/docs/environment/php#built-in-extensions
