### ISSUE TITLE
PASSWORD_ARGON2I missing (v0.3)

### ISSUE THREAD

**Issue by swiffer** [mnapoli/bref#185]
PHP seems to be compiled without argon2i (libsodium). Can this be enabled?

**Comment by mnapoli** [comment]
I did a little check and indeed I don't think we compile with that library.

I'm not familiar with it, could you make a case for this? We cannot afford to include every extension and library in the layer because of space restrictions, we need to select them. We want to include extensions that cover something like 90% of most needs.

**Comment by swiffer** [comment]
It can be used as an alternative (and tentiative more secure?) For bcrypt when using password_* functions.

Seems to be a rather small Addition Size wise?

**Comment by mnapoli** [comment]
Unless it is recommended to be the new default for `password_*` functions and the extension is widely used, I don't think it should be included by default.

It is always possible to provide it via extra layers.

Unfortunately we will have a lot of situations like this where "a little bit of this and a little bit of that cannot hurt". However in the long run this is what cripples a project, and I definitely want to avoid that for Bref. My main focus right now is figuring out what's essential to get the project out there, used and maintainable, and that may be at the expense of some use cases unfortunately.

Again I'm not very familiar with this extension and I may be wrong about how "common" it is. But from what I gather it's not essential for most PHP projects.

**Comment by swiffer** [comment]
Understand that. However most Frameworks and hosting providers implicit having the function available when running php7.2+

https://laravel.com/docs/5.7/hashing#configuration

https://symfony.com/blog/new-in-symfony-3-4-argon2i-password-hasher

**Comment by swiffer** [comment]
(it is not an extension but a compile time switch)

**Comment by mnapoli** [comment]
Thank you for the links, this is interesting.

Indeed it is not an extension, but unless I'm mistaken it requires to set the compile flag *and* include library files right?

As for Symfony and Laravel they both mention the fact that they now support Argon, but they don't recommend it. The closest thing I could find was this sentence in the Symfony post:

> if you are creating a new project, you could consider using this new password hashing algorithm.

This is not a *should*, bcrypt still seems to be the default for now.

**Comment by mnapoli** [comment]
Closing until the situation (or the understanding of the situation) changes.
