### ISSUE TITLE
Run Bref Lambda from an Application Load Balancer

### ISSUE THREAD

**Issue by deleugpn** [mnapoli/bref#187]
AWS announced the possibility to define a Target Group on an Application Load Balancer capable of running a designated Lambda Function. Unfortunately, I tested and confirmed that this is not yet supported by CloudFormation (they'll have to change `Protocol` and `Port` parameters to **Conditional** and allow `TargetType: LAMBDA`). 
I want to manually setup a Target Group pointing to a Lambda function and test it out to see if Bref is already ready to handle the request coming from an ALB. If it works, all we have to do is wait for CloudFormation support to catch up.

**Comment by mnapoli** [comment]
You mention CloudFormation but Bref uses SAM, did you mean SAM?

**Comment by GromNaN** [comment]
This is something discussed here: https://github.com/awslabs/serverless-application-model/issues/721
