### ISSUE TITLE
mapping s3 notifications to console commands

### ISSUE THREAD

**Issue by swiffer** [mnapoli/bref#190]
I'm looking into processing files stored in s3 via different console commands based on their prefix.

For now I've modified the console layer bootstrap and included a specific version in my project.

do you think this is a suitable solution or anything different better in mind?

```php
        // Proxy S3 notifications so they get executed by the right shell command
        if(isset($event['Records'][0]['s3']['bucket']['name']) && $event['Records'][0]['s3']['bucket']['name'] == 'my bucket name'){
            $cliOptions = 'cli options to execute the right command ' . $event['Records'][0]['s3']['object']['key'];
        }
        else {
            $cliOptions = $event['cli'] ?? '';
        }
```

**Comment by mnapoli** [comment]
Hi, I would probably use a PHP function (https://bref.sh/docs/runtimes/function.html).
