### ISSUE TITLE
building image hangs

### ISSUE THREAD

**Issue by prolic** [mnapoli/bref#194]
I just executed this:
`sam local invoke --no-event --region=us-east-1`

output:
```
2019-01-21 20:12:05 Found credentials in shared credentials file: ~/.aws/credentials
2019-01-21 20:12:06 Invoking bin/console (provided)
2019-01-21 20:12:06 arn:aws:lambda:us-east-1:416566615250:layer:php-72:14 is already cached. Skipping download
2019-01-21 20:12:06 Image was not found.
2019-01-21 20:12:06 Building image...
```

where it hangs.

**Comment by prolic** [comment]
Oh, after some more minutes I received an output:

```
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72  Init Duration: 13.66 ms Duration: 0.00 ms      Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 6 MB
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Error: Runtime exited without providing a reason"
}
```

**Comment by mnapoli** [comment]
Could you provide more information, e.g. `template.yaml` and your script so that we can try to reproduce?

Also let us know which OS you are using, what Docker version, how it is installed (e.g. on Windows/Mac it can get ugly), etc. It sounds like something related to Docker.

**Comment by prolic** [comment]
I was changing a lot of stuff and now it works and I cannot reproduce anymore. When I see it again, I'll reopen and try to provide more informations.
