### ISSUE TITLE
Document where the name "Bref" comes from

### ISSUE THREAD

**Issue by prolic** [mnapoli/bref#195]
Why bref? What does it stand for?

**Comment by nealio82** [comment]
It's about halfway down this blog post: https://mnapoli.fr/serverless-php/

> I decided to write Bref to solve those problems.
>
>   The name bref means brief in french, in reference to the ephemeral life of lambdas. French speakers will also enjoy the double meaning of "Bref, j'ai déployé une application serverless" ;)

**Comment by prolic** [comment]
thanks!
