### ISSUE TITLE
PHP Runtime error with a deployed sample Laravel app

### ISSUE THREAD

**Issue by gregmsanderson** [mnapoli/bref#210]
I wonder if anyone else has had, and fixed, this particular error?

So, to test bref with Laravel, I made a brand new app using _laravel new deletethis_,  made the changes suggested on https://bref.sh/docs/frameworks/laravel.html, packaged, and deployed it.

The deployment worked, and PHP works. Since when I requsted the [URL]/Prod it returned "Hello world!" (from the index.php the _init_ command placed at the root).

I deleted that index.php, updated the template.yaml handler to be _public/index.php_ instead, and did another package & deploy.

But when I requested the URL now, I get a black PHP error, showing Laravel is running but is not happy.

`Fatal error: Uncaught RuntimeException: A facade root has not been set. in /var/task/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:234 Stack trace: #0 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(397): Illuminate\Support\Facades\Facade::__callStatic('replaceNamespac...', Array) #1 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(374): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths() #2 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(289): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException)) #3 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(188): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\HttpException)) #4 /var/task/app/Exceptions/Handler.php(49): Illuminate\Foundation\Exceptio in /var/task/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 234`

I set the Laravel log to stderr but there is no more information in Cloudwatch or from tailing the logs. On every path, this happens.

I did wonder if it was anything to do with paths since I'm deploying from Windows 10 and the new env variables do have the Linux style /tmp etc. Whereas maybe when I run config:cache it makes Windows style ones? No idea, kind of clutching at straws! It _sounds_ kind of like a path error with a mention of a "root" but that may be nothing to do with it.

After the usual Google search, I see someone mentions this facade root issue and one person says they fixed it with a typo in the config (but sadly, don't say what) and another with making a new version. But mine is new. Theirs is 5.6 and mine 5.7 but it sounds similar. https://laracasts.com/discuss/channels/laravel/updating-from-55-to-56-resulting-in-a-facade-root-has-not-been-set?page=1

Thanks.

Oh, and ... _should_ fatal PHP errors be shown in production? I've set the env values to _production_. I mean, obviously _here_ it's handy the error _is_ shown else I wouldn't see the issue, but to hide such errors normally do you need to use a custom php.ini to not display errors?

**Comment by mnapoli** [comment]
Hi, thanks for the feedback I've currently started working on updating the guides for Laravel and Symfony so this is helpful.

First:

> should fatal PHP errors be shown in production?

As you mention they shouldn't. They should show up in the Cloudwatch logs, but not in the HTTP responses. This is what I've been testing these last days.

Can you please make sure you are using the latest versions of the runtime for your region (https://runtimes.bref.sh/) and confirm that you see the error/exception trace in production in the HTML response? (if so that's a bug)

Now about your error, I'm suspecting this is because you are deploying your local development install?

I.e. you do `composer install`, make it work locally and then try to deploy that on Lambda using SAM => that means your development files will be deployed (with the dev config and such).

You should instead clear all the cache and let Laravel create it in `/tmp`.

I'll give it a try right now (I might finish this tomorrow though I haven't much time left right now) and I'll report to you if I make it work.

**Comment by gregmsanderson** [comment]
Ah, ok. Thanks for the suggestions.

For the PHP errors, you are correct: I edited the runtime the yaml had by default, changing it to the latest one, and now, yes, no raw PHP error is shown. Instead I get:

{
"message": "Internal server error"
}

Which is great. So that's my fault for not updating it to use the latest runtime.

However there is still _an_ error, which I assume is the same one, just hidden now. I did as you suggest, clearing the cache (I tried both, config: cache and config: clear just to see) and neither help.

Cloudwatch isn't showing the error either. It just shows the request start and finish, with no data in between.

As for what I'm uploading, yes, it is updating the one from my local copy since it's a junk test one that doesn't need to work. In reality it would need to deploy from CircleCI or something. However I've set my local one to use all the production settings and so while it will have uploaded stuff it doesn't need to, and probably shouldn't (like static files), for now that doesn't matter since it was just to test it working. Hmm.

I did wonder if it is to do with the environment variables since presumably the .env file is read and can be loaded? I know normally you'd have a production env or override those variables (like in the yaml, or in the Lambda within the AWS console) for production, but since so far it's not using a database or cache or redis or anything, there is nothing secret that matters in there.

**Comment by gregmsanderson** [comment]
Further to this, I did wonder something.

On https://bref.sh/docs/frameworks/laravel.html it says you should normally run _config:cache_ to cache the config. Which other guides for Laravel say too for performance.  Makes sense.

The guide also says to add this line to bootstrap/app.php:
`$app->useStoragePath(env('APP_STORAGE', $app->storagePath()));`

... but ...

On https://laravel.com/docs/5.7/configuration _it_ says:
**If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files. Once the configuration has been cached, the .env file will not be loaded and all calls to the env function will return null.**

But since we added this line to bootstrap: $app->useStoragePath(env('APP_STORAGE', $app->storagePath())); we **are** calling the env() function from _outside_ the config ... no? So is that returning _null_ ... and if so, causing the missing root error, as it can't figure out the paths?

**Comment by gregmsanderson** [comment]
Ok, I tried random stuff to make it break before the final output to try and get _some_ output on screen to see where it failed. I hacked in some exits within the base of Laravel's code to get it to stop. And success: I got it to output a _whoops_ page which showed the problem: it was trying to store a view, but couldn't.

As shown in the attached image.

You can see in the error it did grab the HTML content of the default welcome.blade.php file, so clearly it's there and could read it. But in trying to save it/read it from a local cache of it, it failed.

I thought that was odd because the image shows it was using the correct prefix suggested in the guide: the _/tmp/storage/framework/views_ one.

Now I'm _guessing_ that Laravel doesn't check that folder path exists _before_ trying to store a file there. That seems odd since how would work on normal Linux servers then (ie non Lambda). However I thought I'd pursue that, and hacked away at the Filesystem.php buried within Laravel. Again, just to see what happened. So I added some:

`if (!is_dir(dirname($path))) {
            mkdir($path, 0755, true);
        }`

... _before_ it calls _file_put_contents_. It does that in three places in that file.

Having done that, and re-deployed, sure enough a _new_ error is shown about files. But it got a bit further. I'm guessing there are other files that work with the files.

So to avoid all this hacking and of course modifying Laravel innards is not a proper solution, I edited the APP_STORAGE and VIEW_COMPILED_PATH to be a folder I know already exists and doesn't need creating: _/tmp_

**And it works.** I get the Laravel welcome page :)

So I'm not sure why my Lambda is not able to create paths that don't exist, since like I say, Laravel surely must have support to do that (for "normal" servers). Is it because of the permissions the custom PHP runtime has vs a local PHP bin perhaps? No idea. But clearly that is where it is failing, since using /tmp works. Now maybe we could leave it as /tmp all the time, but I'm not sure if any files could conflict if we do that. Not sure how it works internally. I assume there is a good reason for using different folders for various cached content which that would stop as they'd all go into one.

![why-it-didnt-work](https://user-images.githubusercontent.com/10390169/51938332-bb28e780-2404-11e9-8965-59b570ab6f23.jpg)

**Comment by gregmsanderson** [comment]
Oh. Thinking about this, of course the issue does not normally arise (on normal servers). Since Laravel's default folder structure, which would be uploaded, _already_ has the _/storage/framework/views_ folder. Just like it has a _/storage/framework/cache_ etc. So on _non_-Lambda servers, a lack of _does-the-folder-exist_ check would not be an issue. Since the folder _would_ exist, out of the box. In _that_ case, it would just be a case of making sure the folder was writable.

_Although_ this doesn't explain how you previously managed to make Laravel work using your suggested values, since the Lambda server/container would not have those folders in /tmp.

But ignoring that it would explain it for my deploy.

The question is whether it is safe to use /tmp for all the things or whether there needs to be a separation.

**Comment by mnapoli** [comment]
Thanks a lot for those details. I managed to make it work as well and update the documentation (here #218) and the demo repository (here https://github.com/mnapoli/bref-laravel-demo).

**Comment by gregmsanderson** [comment]
Great!

Though I'm still not quite sure how you are getting it to work since I had to use /tmp. That would be fine but I'm not 100% sure that's ok to do (using one folder for different things Laravel expects to be in separate folders)

![env-path](https://user-images.githubusercontent.com/10390169/52056102-38fe0780-2559-11e9-835d-c590ab23fdc6.jpg)

**Comment by mnapoli** [comment]
See this part: https://github.com/mnapoli/bref/pull/218/files#diff-08419559457efa0efc6b72432cefcbb7R99

**Comment by gregmsanderson** [comment]
Ah ... Yep, now I see.

Great work.
