### ISSUE TITLE
Issue with Laravel when session driver is cookie

### ISSUE THREAD

**Issue by gregmsanderson** [mnapoli/bref#211]
Not quite sure on this, but I was tempted to try using:

`SESSION_DRIVER=cookie`

... given that I have minimal data to store, and it's scalable as it has no backend store (Redis, MySQL etc) needed (at the expense of larger http headers). That stores the session data in the cookie, rather than the normal PHP approach which simply sends a session ID which in turn matches a backend store.

(I'm not actually interacting with the session in the code here, as this is from just looking at the welcome page, but I _assume_ Laravel records data about the view last looked at etc in there by itself and so that's why it gets sent)

When running locally that works fine. Two cookies are set by Laravel, a app one (like appname_session) and also a second one (which I assume is used internally within Laravel to ensure the first cookie has not been tampered with, as it looks encrypted).

However the response from Laravel on Lambda only sets one of these cookies, the second one.

I assume as a consequence, when you request the page a second time, a new one of those signed/encrypted cookies gets set (and of course the previous one is sent in the request). And a new one on the third is set. And so on. Each with a new name=value. And sure enough, as they accumulate, eventually you reach the http limit and get an error (as shown in the other image attached).

So ... I guess this particular issue can be avoided by not using the SESSION_DRIVER=cookie. As then I assume only one cookie is sent, which has the session ID in.

_Although_ ... I wonder if a cookie is using as part of the CSRF protection ... in which case, again, if only one cookie can be sent, and you have an app cookie _and_ a CSRF cookie, whether only one is sent. Hmm. That needs further investigation.

![no-app-cookie-sent](https://user-images.githubusercontent.com/10390169/51940368-b286e000-2409-11e9-907c-4167c63aa316.jpg)
![consequence-of-too-many-cookies](https://user-images.githubusercontent.com/10390169/51940369-b31f7680-2409-11e9-98d0-49f244372c2c.jpg)

**Comment by mnapoli** [comment]
Closed in favor of #213
