### ISSUE TITLE
Symfony: the terminate event must run synchronously

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref#214]
By default Symfony runs the terminate event asynchronously when using PHP-FPM.

That will not work as expected here because when PHP-FPM sends the response, Bref sends it to Lambda and the lambda instance is then freezed. The terminate event will then probably run on the next invocation.

We need to document how to disable this behavior.

**Comment by j-tec** [comment]
i can just provide the logs i see in CloudWatch 

`Fatal error: Uncaught Hoa\Socket\Exception\Exception: Client returns an error (number 111): Connection refused while trying to join unix:///tmp/.bref/php-fpm.sock. in /var/task/vendor/hoa/socket/Client.php:191
Stack trace:
#0 /var/task/vendor/hoa/stream/Stream.php(219): Hoa\Socket\Client->_open('unix:///tmp/.br...', NULL)
#1 /var/task/vendor/hoa/stream/Stream.php(297): Hoa\Stream\Stream::_getStream('unix:///tmp/.br...', Object(Hoa\Socket\Client), NULL)
#2 /var/task/vendor/hoa/stream/Stream.php(178): Hoa\Stream\Stream->open()
#3 /var/task/vendor/hoa/socket/Connection/Connection.php(197): Hoa\Stream\Stream->__construct('unix:///tmp/.br...', NULL)
#4 /var/task/vendor/hoa/fastcgi/Responder.php(183): Hoa\Socket\Connection\Connection->connect()
#5 /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php(103): Hoa\Fastcgi\Responder->send(Array, '{\n\t"DoctrineEntity...')
#6 /opt/bootstrap(26): Bref\Runtime\PhpFpm->proxy(Array)
#7 /var/task/vendor/mnapoli/bref/src/Runtime/LambdaRuntime.php(58): {closure}(Array)
#8 /opt/bootstrap(27): Bref\Runtime\LambdaRuntime->processNextEvent(Object(Closure))`

**Comment by j-tec** [comment]
The previous connection timed out, this was also the response the lambda returned. 
`REPORT RequestId: afeb2cb2-3334-45cd-bb9b-199765833828 Duration: 30005.81 ms Billed Duration: 30000 ms Memory Size: 128 MB Max Memory Used: 82 MB `

**Comment by mnapoli** [comment]
OK thank you, that makes sense then. We should modify the PHP max execution time to 29 seconds then.

Any other idea to address this (e.g. if users change the API Gateway timeout below 30 seconds) is welcome. Maybe we could use the `context` variable (not available in Bref in the current version) to determine how much time is left and update the PHP max execution time on the fly.

**Comment by mnapoli** [comment]
Oops #220 is about the bug I was talking about. I've move my comment above into #220.

**Comment by vdechenaux** [comment]
Maybe we can add `disable_functions=fastcgi_finish_request` to php.ini ?
`\function_exists('fastcgi_finish_request')` returns false and Symfony will not use it

**Comment by mnapoli** [comment]
@vdechenaux so simple I love it! Very nice idea and it would work with all frameworks, that's awesome!

**Comment by mnapoli** [comment]
PR: #251

**Comment by ashish-dirkmedia-de** [comment]
have put `disable_functions=fastcgi_finish_request` to php/conf.d/php.ini 
But still get this error after previous request time out
