### ISSUE TITLE
Update documentation for PHP configuration

### ISSUE THREAD

**Issue by pmayet** [mnapoli/bref#217]
Hi,

Since this commit [https://github.com/mnapoli/bref/commit/90314f50b95a312838a3878d1b842e2e7c68e34b](https://github.com/mnapoli/bref/commit/90314f50b95a312838a3878d1b842e2e7c68e34b), the scan directory for customizing is now by default `php/conf.d` instead of `php/config.d`.

@mnapoli do you want PR ?

**Comment by mnapoli** [comment]
Right the documentation is not 100% up to date sorry, it seems I partially updated it 🤔  (e.g. https://github.com/mnapoli/bref/blob/master/docs/environment/php.md)

Yes a PR would be awesome!
