### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by prolic** [mnapoli/bref#222]
I have a lambda function that does something (obviously), and I found it to be running very slow, so I compared that to the execution speed on my local machine. Here's some output (I did not include the init duration), where I used `echo microtime(true) . PHP_EOL;` at the beginning of the function, at the end and a few times in between.

Local -> total execution time is 182ms
```
1549018445.1846
cache.pages.v1 @ 2000
1549018445.185
1549018445.1851
1549018445.1934
1549018445.1969 connected
1549018445.1969
1549018445.2028 event read
```

Lamdba -> 24012ms
```
1549018411.3753                                                                                
cache.pages.v1 @ 2500
1549018411.3762
1549018411.3762
1549018412.0155
1549018412.3984 connected
1549018412.3985
1549018413.7765 event read
```

Ok, I create 1-2 server connections and dns resolving maybe takes a little longer than on a local machine, I get that, and my machine might be faster, so I can expect some difference.

But lamdba is ~ 132 times slower than when I run this script locally.

Have you experienced similar results?

**Comment by prolic** [comment]
I started measuring within the lambda function itself, so it's really pure PHP execution time. Need to try with more memory, but 128MB is usually enough for my usecase, will try that however.

**Comment by wysow** [comment]
Just my 2 cents but as far as I understand how lambda is dealing with memory the value of RAM is directly linked to the allocated CPU power, so 128MB is linked to a "little" CPU power, and more RAM = more powerful CPU. Am I right @mnapoli ?

**Comment by mnapoli** [comment]
Yes that's it

**Comment by prolic** [comment]
I can confirm that increasing the memory limit, I could improve the performance by an order of magnitude. It's still way slower compared to my notebook, but the speed is in acceptable range.
