### ISSUE TITLE
500 Internal Server Error on CloudFormation

### ISSUE THREAD

**Issue by deleugpn** [mnapoli/bref#239]
I just spent three days going back and forth between AWS Support to try and get to the bottom of a 500 internal server error on CloudFormation when trying to setup Lambda

```
An error occurred and the request cannot be processed. (Service: AWSLambdaInternal; Status Code: 500; Error Code: ServiceException; Request ID: xxxxxx)
Stack ID(s) / Stack ARN: xxxxxxxxx
```

I wanted to create this topic just to try and help people by indexing the problem and what worked for me. My issue was on the layer ARN region. Instead of **- arn:aws:lambda:eu-west-1:209497400698:layer:console:1** I had a typo on the region which led to **- arn:aws:lambda:eu-`wast`-1:209497400698:layer:console:1** and as of today, this typo is not being validated by CloudFormation, which lead to a nasty internal server error that took a lot of time even for AWS Support Engineers to find.

Hope this help people avoid wasting time.

**Comment by mnapoli** [comment]
:+1:, I've have a problem of the kind at some point (using the wrong region) and say as you it was very cryptic to resolve :/

Hopefully they improve that both in CloudFormation and `sam local`…

**Comment by otaviomacedo** [comment]
For anyone reading this and still having the same problem, here is my recommendation: check if there is any parameter with a null or empty value. In my case, I was using a parameter to construct the principal for a Lambda permission, but I forgot to pass the value to the parameter and ran into this obscure issue.

**Comment by Angelina1984** [comment]
For us it was typo in ARN: 
```
"layers": [
          "arn:awscloud:lambda:us-east-1:XXXX:layer:XXX_nodejs:1"
        ],
```
