### ISSUE TITLE
PHP logs accidentally sent to the HTTP response

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref#247]
This is a follow-up of #216 

> PHP-FPM sends logs in the FastCGI output under the key `PHP message:`. Those lines end up in the HTTP headers. They are parsed by Hoa/FastCGI as response headers.

**This issue is currently fixed (by #216), but in a hacky way.**

However we discovered with @vdechenaux that the issue has been fixed upstream in Hoa\FastCGI (see https://github.com/hoaproject/Fastcgi/pull/19) and we are now waiting for a new release to use it: https://github.com/hoaproject/Fastcgi/issues/23

This issue is here to track this.

**Comment by Hywan** [comment]
New release should fix your issue.

**Comment by vdechenaux** [comment]
Should be closed, fixed by https://github.com/mnapoli/bref/commit/e34c361e8e2f889b5f1a723e8864b49817caae5b

**Comment by mnapoli** [comment]
👍 	forgot to close this thanks

**Comment by Hywan** [comment]
:+1:
