### ISSUE TITLE
Could not  find driver error when trying to connect to RDS

### ISSUE THREAD

**Issue by ppbittencourt** [mnapoli/bref#260]
I'm creating a HTTP application on Laravel to be served on by Lambda. This application needs a database, so i created one in RDS and putted the Lambda on the same VPC as the database (using subnets with NAT access). But when i try to access my API Endpoint i get the following error:

![error](https://user-images.githubusercontent.com/48369923/54062314-06909b80-41e4-11e9-9fe7-6bf48e708ce1.JPG)

I already connect to the database using a local project, so i really don't know what to do now. Any ideas?

**Comment by ppbittencourt** [comment]
Solved the issue. Just had to create a /php/conf.d/php.ini file with extension=pdo_mysql on the root of the project.

**Comment by thaisanly** [comment]
I have try this method but cause issue `{"message": "Internal server error"}`

**Comment by AlessandroMinoccheri** [comment]
Could you please open a new issue @thaisanly with your case? This issue  has been closed for a year

**Comment by akondas** [comment]
I am adding a link to the documentation (for posterity :wink:):
https://bref.sh/docs/environment/php.html#extensions-installed-but-disabled-by-default
