### ISSUE TITLE
Adding ALB Support

### ISSUE THREAD

**Issue by atrope** [mnapoli/bref#262]
Hello,
I Am working on adding ALB Support (with multi value headers) to bref.
https://aws.amazon.com/pt/blogs/networking-and-content-delivery/lambda-functions-as-targets-for-application-load-balancers/

I Already managed to it without a problem.
The only issue is that we also need to alter Hoa Responder class to process multi headers, how should we do it?
First update there and then here?

Thanks!

**Comment by mnapoli** [comment]
Awesome!

I see you've opened https://github.com/hoaproject/Fastcgi/pull/28 you could start with a pull request that requires your branch? Your PR would be blocked until Hoa merges your PR and a new release is tagged, but at least we can start reviewing your work and save some time?

**Comment by mnapoli** [comment]
I just saw that you opened #263 so nevermind my comment above :)

Let's see if we can get things merged in Hoa.

**Comment by atrope** [comment]
@mnapoli  great :) 
I cant find the pretty xml file to fix the rest of the issues there, if you could kindly show me which one i should use i can gladly fix the pretty error that is giving me in the PR
Thanks!

**Comment by mnapoli** [comment]
You can find the errors in the "Checks" tab: https://github.com/mnapoli/bref/pull/263/checks?check_run_id=76095407

You can also run `vendor/bin/phpcs` locally and it should print the warnings.

**Comment by mnapoli** [comment]
Great, I'll try to look into this this week, hopefully I can help writing the tests and the documentation.

**Comment by aknosis** [comment]
@atrope  Seen any perf benefits vs. via API Gateway?

**Comment by atrope** [comment]
@aknosis sorry for late reply, No Performance benefits, but i can have healthchecks(always warm lambdas), and pricing is a lot cheaper for M(B)illions  of calls. Also i Have CF in front of the function, making it globally cached and i can configure CF as i want

**Comment by atrope** [comment]
@mnapoli if we change to hollodotme, we will be able to merge this, because i will be able to parse the multi valued header within the request process (hollodotme gives us the raw response, i will also make a PR so it supports multi valued header, but we don't need to wait for it :))

**Comment by mnapoli** [comment]
:+1:

**Comment by Hywan** [comment]
Muti-headers support is under review, ready to be merged in hoa/fastcgi, https://github.com/hoaproject/Fastcgi/pull/28#issuecomment-487869265.

**Comment by aknosis** [comment]
Would it be desirable to have another prompt as part of `init` that lets you specify ALB vs APIGW if you were to choose the HTTP option?

**Comment by mnapoli** [comment]
@aknosis I don't think it would make sense, using ALB is an advanced use case. I want to keep Bref's onboarding simple and easy.

It could make sense however to document how to use ALB, but in a separate documentation article.

**Comment by mnapoli** [comment]
@atrope Serverless added support for ALB: https://github.com/serverless/serverless/pull/6073
