### ISSUE TITLE
Image uploaded to S3 gets corrupted

### ISSUE THREAD

**Issue by ppbittencourt** [mnapoli/bref#271]
I'm making a serverless laravel application, and i need to be able to upload images to S3 via form. I tested locally and it uploads and retrieves the image just fine from S3, but when i try the same code in my serverless application, the uploaded file in S3 arrives corrupted.

That's the code i'm using to upload the images:
![upload](https://user-images.githubusercontent.com/48369923/54401635-3a1d6b00-46a7-11e9-98f0-31c7c52b6473.JPG)

I tried uploading other types of files, but all of them arrive corrupted in S3, except for txt.
I already searched a lot and couldn't understand the reason of this.

**Comment by ppbittencourt** [comment]
Just found the solution for my problem. I had to go to API Gateway, and under Settings add the media binary type multipart/form-data, save and redeploy the API. After that the upload worked!

**Comment by ashish-dirkmedia-de** [comment]
Yes it works thanks.

**Comment by atifshamim** [comment]
it worked for me as well

**Comment by mnapoli** [comment]
For reference here is the documentation: https://bref.sh/docs/use-cases/http/binary-requests-responses
