### ISSUE TITLE
Soap Extension

### ISSUE THREAD

**Issue by jsamouh** [mnapoli/bref#283]
Hi @mnapoli 

First of all, thanks a lot for this project. Using bref to deploy lambda function in PHP works great :-)

I work on a company that starts to use a lot of lambda functions.
And we have to interact with several services that propose API with Soap protocol.

Is there a possibility to add this extension (disable by default) in your layer, so we won't create our custom layer ?

Thanks,
Jordan

**Comment by atrope** [comment]
@mnapoli  for this you just need to add the `--enable-soap` in PHP build

**Comment by mnapoli** [comment]
@jsamouh I merged #289 and I'll wait for #291 with a fix before building new runtimes (should not be long).
