### ISSUE TITLE
Help with Imagemagick

### ISSUE THREAD

**Issue by yousafs** [mnapoli/bref#284]
Firstly thanks @mnapoli  for helping us reimagine our infrastructure in Lambda!
@atrope thanks for your hints on Imagemagick earlier.

Sorry to trouble you all with a user issue but I am stuck trying to get Imagemagick working in bref. 

I have previously made a simple mod to the php.Dockerfile to enable mysqli and this worked perfectly. I rebuilt with `make build` and uploaded a custom bref layer to my own repo - all good.

I have now tried to do the same with ImageMagick / Imagick but I am constantly getting:

```
Fatal error: Uncaught ImagickException: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/556 in /var/task/s3-php-info.php:28
Stack trace:
#0 /var/task/s3-php-info.php(28): Imagick->__construct('image.png')
```

when trying to open a png (same happens with JPG).

All I have done is add the following to php.Dockerfile after the existing PECL declarations:

```
# make sure we use the right release for Lambda
RUN sed -i 's/releasever=latest/releaserver=2017.03/' /etc/yum.conf

RUN LD_LIBRARY_PATH= yum install -y ImageMagick-devel
RUN pecl install imagick

# test to see if it worked
RUN convert -list configure

```
I have tried many things to rectify this but I'm stuck. One thing I have realised is that I seem to have ended up with two versions of Imagemagic.

If inside my php file in Lambda I run ` print_r(Imagick::getVersion ()); ` I get:

```
Array
(
    [versionNumber] => 1800
    [versionString] => ImageMagick 7.0.8-34 Q16 x86_64 2019-03-24 https://imagemagick.org
)

```
which seems to be 7.0.8

If I use the command line to get a version using ` print shell_exec ("cd /opt/bref/ && convert -list configure"); ` i get

```
..
EXEC-PREFIX   /usr
EXECUTABLE_PATH /usr/bin
FEATURES      OpenMP 
FILTER_PATH   /usr/lib64/ImageMagick-6.7.8/modules-Q16/filters
HOST          x86_64-redhat-linux-gnu
INCLUDE_PATH  /usr/include/ImageMagick
LDFLAGS       -L/usr/lib64 -L/usr/lib
LIB_VERSION   0x678
LIB_VERSION_NUMBER 6,7,8,9
LIBRARY_PATH  /usr/lib64/ImageMagick-6.7.8
LIBS          -lMagickCore -llcms2 -ltiff -lfreetype -ljpeg -lfontconfig -lXext -lSM -lICE -lX11 -lXt -llzma -lbz2 -lz -lm -lgomp -lpthread -lltdl
NAME          ImageMagick
PCFLAGS       -fopenmp
PREFIX        /usr
QuantumDepth  16
RELEASE_DATE  2016-06-22
SHARE_PATH    /usr/share/ImageMagick-6.7.8
SVN_REVISION  8903
TARGET_CPU    x86_64
TARGET_OS     linux-gnu
TARGET_VENDOR redhat
VERSION       6.7.8
WEBSITE       http://www.imagemagick.org

```

which seems to be 6.7.8

Either way it would seem PHP/Imagick cant find something - the shared libraries or delegates??

Any help would be appreciated!

**Comment by yousafs** [comment]
OK - so I've figured it out and got it working - I was being stupid!
Keep up the amazing work everyone!

**Comment by nealio82** [comment]
@yousafs what was it that you figured out? is it something other people are likely to run into?
