### ISSUE TITLE
Enable bcmath extension

### ISSUE THREAD

**Issue by tiagobrito** [mnapoli/bref#292]
`bcmath` extension is currently being used in important libraries such as `google/protobuf` (directly) and indirectly by other relevant libraries eg: `google/cloud-vision` and more.

@mnapoli What you think about adding it to the list of enabled extensions?

**Comment by deleugpn** [comment]
`laravel/telescope` also uses it.

**Comment by mnapoli** [comment]
New runtimes include bcmath by default!
