### ISSUE TITLE
Enable sockets opt-in on php runtime

### ISSUE THREAD

**Issue by alborq** [mnapoli/bref#301]
Actually sockets it not enable on php runtime. 

So we can't use all [Sockets functions](https://www.php.net/manual/fr/book.sockets.php)

Use Case : 
- Log on remote SysLog with Monolog UDP
- Send Metrics via InfluxDB

**Comment by bubba-h57** [comment]
@mnapoli if you approve, I will create the pull request.

**Comment by mnapoli** [comment]
:+1: makes sense indeed, could you check as well that it doesn't make the layers noticeably fatter?

**Comment by mnapoli** [comment]
Runtimes have been built and published, thank you @bubba-h57!

**Comment by alborq** [comment]
Thanks both of you :)
