### ISSUE TITLE
Layer to share pieces of code

### ISSUE THREAD

**Issue by matiux** [mnapoli/bref#304]
I would like to create my composer library and I'd like to share this library between some lambda. 

Rather than install this package in the vendor folder of any lambda, I'd like create a layer and share this. Is it a bad idea? Is there some documentation to achieve this?

**Comment by mnapoli** [comment]
Hi, I'm not sure it would make sense as releasing new versions would seem to be harder to me. Also dealing with autoloading might be harder.

And to answer your second question there is no documentation regarding that.
