### ISSUE TITLE
How to run code only once on cold start?

### ISSUE THREAD

**Issue by prolic** [mnapoli/bref#326]

**Comment by mnapoli** [comment]
You would need to write your own `bootstrap` file, either in a layer or straight in your repository.

**Comment by prolic** [comment]
Is there any example? Where is this bootstrap file in bref?
A little background: I want to use libre-office serverless in aws lamdba and need to extract the zip file on cold start.

**Comment by prolic** [comment]
That's what I did already, something like:

```
if (! is_dir(....)) {
    // download
    // unzip
}
```

However it would be nice to be able to add custom bootstrap handler (or a hook to add addtional logic). I can make this bref thing work on aws lambda, incl some environment variables, roles, vpc, resources, etc, but I still lack some basic knowledge on how to create custom layers to add something to cold start for example.

Documentation additions would be awesome, as I think i'm not the only one (but maybe I am, haha).

**Comment by mnapoli** [comment]
:+1:, to create a custom bootstrap you can create a file named `bootstrap` in your project.

I'm going to close this as there is already an issue to add documentation for custom layers. I don't think creating a custom bootstrap should be documented and advertised (yet) as it's pretty advanced. As for your original need I think your solution is exactly what should be done: it is simple and portable.
