### ISSUE TITLE
Move to the Bref organization on GitHub and Packagist

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref#328]
We have passed 1000 stars on GitHub 🎉 

It's time for Bref to move to its own organization: https://github.com/brefphp

I did it previously for PHP-DI and this is what I remember:

- move the project (do not fork it!) on GitHub: we will keep all issues, history, stars, watchers, etc. The old repository URL will redirect to the new. This works as well for git URLs IIRC.
- change `composer.json` to use the `bref/` vendor name
  - the packagist project will be *created*, not migrated
  - the old package will still exist (its stats will not be migrated to the new one): how can we mark the old one deprecated? should we push a last release on that name?

Users will have to change their composer.json to use `bref/bref` instead of `mnapoli/bref`.

This could be released a `0.4.0` but is it necessary?

**Comment by jenschude** [comment]
You could also add a replace `mnapoli/bref: ^0.3` to the composer.json

**Comment by atrope** [comment]
While it is not necessary to move up to `0.4.0`  i think its better in terms of organization, so 0.4.0 would be the first release as organization :1st_place_medal:

**Comment by mnapoli** [comment]
See #342
