### ISSUE TITLE
Feature proposal: Google Cloud Run and OpenFaas Support

### ISSUE THREAD

**Issue by Rodenastyle** [mnapoli/bref#329]
Google Cloud Run, Azure and OpenFaas are using Dockerfiles as layer system. Bref already has the Dockerfiles but only supports requests from AWS API Gateway (Proxy mode).

Two of the main benefits of serverless world is deployments price and that it´s pretty the same execution between providers. What if we get all the logic around API Gateway/ALB behind some conditionals then continue the common flow so all the providers become supported?

**Comment by mnapoli** [comment]
I think this is more complicated as this involves all the documentation, the bootstrap files, the configuration, etc. Everything is tailored for AWS.

The reason for this is documented here: https://bref.sh/docs/#what-is-bref

There are no plans in the short term to support other providers given the amount of effort it would be.

Additionally I'd rather Bref does one thing well than many things poorly. Supporting more providers with a high level of quality is a huge effort that cannot be done without enterprise support.

Closing for now, we might revisit in the future.
