### ISSUE TITLE
Bug: PATCH/PUT methods doesn't allow body content

### ISSUE THREAD

**Issue by Rodenastyle** [mnapoli/bref#330]
Only POST requests are allowed to have body, but PATCH and PUT ones usually need it as well.

**Comment by mnapoli** [comment]
PATCH and PUT should support HTTP requests with a body. This behavior is tested here: https://github.com/mnapoli/bref/blob/6c8c4de1ea706bb66f5ab2544860d8a8d9f9bfbe/tests/Runtime/PhpFpmTest.php#L218-L302

Those tests were added in #297

Could you write a test that reproduces the bug you are seeing?

**Comment by Rodenastyle** [comment]
Seems to be solved, identified before April 8th.
