### ISSUE TITLE
symfony flash not working

### ISSUE THREAD

**Issue by Darkbelg** [mnapoli/bref#341]
So i have been developing a website with symfony. A few issues have come up which i don't really know what to do with. When i developed i developed using the build in symfony server. which is great but doesn't represent the serverless. I learned that this function `$form->isValid()` doesn't work on serverless. I have no idea why and i don't really know how to debug it. I just removed the check in my if and it works. But now i have hit another issue with the flash messages aren't working. So i looked at the local-development of the documentation execute the write code to boot up a docker instance. It works and i am able to reproduce the problem. But i have no idea of how to debug. Every time i do a dump i get a 500 error i need some more documentation and support how to debug this. I am able to start in dev mode but i just get the message `An error occurred while loading the web debug toolbar.`. Not sure what to do or where to find the proper logs. Also the urls on the local development lead to 404. Can somebody help me ?

Also How do i do 404 can i do this with symfony or with cloudflare ? Now i just have `{"message":"Missing Authentication Token"}`

**Comment by mnapoli** [comment]
Hi, I think you need to configure the session to be stored in a persistent backend like a database or Redis. If the sessions do not work then Symfony flash will not work.

**Comment by Darkbelg** [comment]
Is it possible to store the file sessions in the tmp folder like the logs and cache ? https://symfony.com/doc/4.1/session/sessions_directory.html OR don't you think that would solve my problem ?

**Comment by mnapoli** [comment]
It wouldn't because the filesystem is not shared between multiple instances of a lambda. You have no guarantee that all requests for a specific person will be all handled by the same lambda, so the session might be lost along the way.

**Comment by Darkbelg** [comment]
Ok i will do flash messages with cookies then. Or do you know any alternatives ? Sessions seem pretty important are you going to add documentation about this ? Or how do you do sessions in php ?

**Comment by mnapoli** [comment]
Agreed, that's something I need to document but unfortunately there is a lot of work to do at the moment ^^
