### ISSUE TITLE
Post deploy hook

### ISSUE THREAD

**Issue by t-geindre** [mnapoli/bref#38]
A post deploy event would be very usefull.

For instance, we'd like to run a cache warmup command after deploying our lambda.

**Comment by mnapoli** [comment]
Most of the time a post-deploy hook doesn't make sense on FaaS because the lambda's filesystem is readonly and the rest (`/tmp`) can contain temporary files but those are lost on next executions.

If you need to generate a cache it's usually better to generate it before deploying?

**Comment by t-geindre** [comment]
You're right about the file system.
But that's still relevant for a Redis cache for instance.

**Comment by t-geindre** [comment]
Actually, that's exactly what I was thinking after posting my last message.
Since we already use Makefile to run our deployments, we can add more tasks after `bref deploy`.
