### ISSUE TITLE
Add support for the Phalcon framework

### ISSUE THREAD

**Issue by gregmsanderson** [mnapoli/bref#45]
It would be great if Phalcon (https://phalconphp.com) could be supported.

Unlike most frameworks (Slim etc) it is compiled as a PHP extension. Given that, I did _wonder_ if the commands from their example Dockerfile, such as [https://github.com/phalcon/dockerfiles/blob/master/php-fpm/7.2-min/Dockerfile](https://github.com/phalcon/dockerfiles/blob/master/php-fpm/7.2-min/Dockerfile) ... but there are a bunch more if that's not the right one ... could be added.

It is then enabled like other PHP extensions by adding the line 'extension=phalcon.so' to php.ini,

Thanks.

**Comment by mnapoli** [comment]
Good idea! From their documentation it seems to be simpler: https://docs.phalconphp.com/fr/3.3/installation#installation-sources

```
git clone https://github.com/phalcon/cphalcon
cd cphalcon/build
sudo ./install
```

Extensions (`*.so` files) are then copied to be packaged with Bref, see https://github.com/mnapoli/bref/blob/master/bin/php/build.sh#L32 You can try to give it a go, [this](https://github.com/mnapoli/bref/blob/master/bin/php/build.sh) is the script used to create the Bref archive. For your tests just comment out the `aws s3 copy` line because you will not be able to upload the archive on the S3 bucket.

**Comment by gregmsanderson** [comment]
Thanks, I'll give that a try. It would be nicer to not have to re-compile Phalcon on every deploy, if that's what would happen if I added it to that build.sh.

I wonder if I could compile it once, making the phalcon.so, then check for its existence. Only if it doesn't exist, compile it.

**Comment by mnapoli** [comment]
The Dockerfile and `build.sh` in this repository are not executed for users. They are executed once to build the PHP binary and its extensions, it's all zipped and uploaded to a S3 bucket that I own.

Then when users do `bref deploy` it downloads the zip, unzip it and deploys the lambda with the PHP binary and the extensions.

So it's not recompiled every time.

**Comment by gregmsanderson** [comment]
Ah ... so it would only compile once. Awesome!

**Comment by gregmsanderson** [comment]
Yeah ... this likely isn't going to work.

I managed to create a custom PHP binary and got it to compile Phalcon by modifying the Dockerfile. So it had the phalcon.so extension. However to then make _that_ work with bref, it seems you need an adapter for each framework. And Phalcon has yet to support PSR 7 and so I assume that is not possible. Since that seems to be the basis of the other adapters. So looks like Phalcon can't be supported.

**Comment by mnapoli** [comment]
Right not easy! I did write a bridge for Laravel and Symfony, for example: https://github.com/mnapoli/bref/tree/master/src/Bridge/Symfony Those do not support PSR-7. That wasn't easy because it was like moving in the dark.

**Comment by gregmsanderson** [comment]
I saw, yes. But ian't see how to make similar ones for Phalcon. I had hoped it would be similar, but seems not. I did locate this: https://github.com/codeup-berlin/phalcon-psr which seems to be along similar lines, adapting it, however there is no explanation of how to use it.

**Comment by mnapoli** [comment]
Looking back on this issue for now I'll close this as I do not intend to add support for Phalcon. If anyone is interested to work on this please let me know here.

I would be okay for supporting it if it doesn't impact the current tooling/architecture too heavily.
