### ISSUE TITLE
Progress bar does not appear/update

### ISSUE THREAD

**Issue by gregmsanderson** [mnapoli/bref#46]
Running vendor/bin/bref deploy makes a progress-bar placeholder appear, however that does not update. It just sits empty. Even after the deploy successfully completes after a few minutes, it is still empty. It happens on the first deploy, and also on subsequent ones (updates).

This is on Ubuntu 16.04 if that helps.

The time taken next to it also does not update during an upload. That would be good to have too.

Thanks.

![no-progress-bar](https://user-images.githubusercontent.com/10390169/43225101-3d2ff4a6-9050-11e8-9146-f6d3494dd9c9.jpg)

**Comment by gregmsanderson** [comment]
Hello,

No problem. I tried that, and the progress bar worked as expected. I just tried the default, plain Symfony bar (as shown in the image). That seems to be working fine using this script.

![progress-bar](https://user-images.githubusercontent.com/10390169/43227156-cea25b90-9055-11e8-8fed-93c3593e3c63.jpg)

```<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Formatter\OutputFormatter;

$output = new ConsoleOutput();
$output->setFormatter(new OutputFormatter(true));

echo "Starting ...\n";

// creates a new progress bar (20 units)
$progressBar = new ProgressBar($output, 20);

// starts and displays the progress bar
$progressBar->start();

$i = 0;
while ($i++ < 20) {
    sleep(1);

   $progressBar->advance();
}

// ensures that the progress bar is at 100%
$progressBar->finish();

echo "\nDone!\n";```

**Comment by mnapoli** [comment]
Thank you for trying all that! I'm thinking 2 things could cause the issue:

- I overloaded the progress character: `$progressBar->setBarCharacter('░');` https://github.com/mnapoli/bref/blob/master/src/Console/Deployer.php#L213
- I output stuff above the progress bar while it is being re-rendered: https://github.com/mnapoli/bref/blob/master/src/Console/Deployer.php#L88-L90

If you still have your script around maybe you could try with `$progressBar->setBarCharacter('░');`?

**Comment by gregmsanderson** [comment]
Ah, that could be it.

I tried again with _that_ progress bar character, and the bar was invisible. The '>' was still at the end, and that did progress, but perhaps your formatting removes that.

When I tried another character, like:
$progressBar->setBarCharacter('*');
... it worked, and the bar filled (in my test code anyway). So what I might do is try editing your code locally to overwrite that line, try a deploy, and see if I see a bar. If so, it is that character that's causing it.

**Comment by gregmsanderson** [comment]
Hello,

Yes, changing the character made the bar appear. I tried a * but I guess any ASCII would do.

![updated-character](https://user-images.githubusercontent.com/10390169/43232041-f73a2784-9066-11e8-9e44-2793863b99d5.jpg)

However - and this may be to do with _what_ the progress bar is monitoring - it doesn't update during an upload. It (and the time) does not change. It _only_ seems to reflect the steps completed. Perhaps that is how it is meant to work, treating each step as taking an equal time. But since the upload of the Lambda, the last bit, is by _far_ the slowest bit of the process (for me on my connection anyway!), I would find it helpful if a/the bar monitored the upload progress (as in X MB/Total MB).

**Comment by mnapoli** [comment]
I've changed the characters so that it works on Ubuntu too (I reverted back to Symfony's default style).

As for the progress it is very hard to use serverless' progress, I won't work on it but feel free to do so and send a PR if you want to.
