### ISSUE TITLE
Thoughts about security

### ISSUE THREAD

**Issue by gregmsanderson** [mnapoli/bref#49]
Hello

1) I noticed in order to make an app work, the base/entry file is changed from the normal /public/index.php to a /bref.php in the root. I'm used to the normal web server (like nginx) approach - where the root folder is defined in the nginx conf to be something like /public, and then code, like /app, is _outside_ of that. So /app would be a sibling of /public and can't be got to using a web request. So I wondered is that an issue where _everything_ is in the same folder when served using bref?

Or is it not an issue as presumably there isn't an equivalent of try_files where a file will be served, so perhaps someone can't request /path/to/something.php to access settings etc.

2) Again, from a normal web server background, I would edit php.ini to lock it down a bit. Disabling file uploads, turning off _allow_url_fopen_, things not needed. Presumably the PHP bref uses is using the default ini ... perhaps this?
https://github.com/php/php-src/blob/master/php.ini-production
Is that an issue, security-wise?

Thanks.

**Comment by mnapoli** [comment]
Thanks for asking these questions!

1. This is not an issue. AWS lambda called via HTTP (i.e. it means via API Gateway) works by calling *a single file*: `handler.js` which calls `bref.php`.

As far as I know there is no way for HTTP clients to call another file. So we don't have the same problem as Nginx/Apache setups where we need a `public/` folder.

> Or is it not an issue as presumably there isn't an equivalent of try_files where a file will be served, so perhaps someone can't request /path/to/something.php to access settings etc.

That's correct.

2. This is the `php.ini` used by default by bref: https://github.com/mnapoli/bref/blob/master/template/php.ini

You can set flags through `.bref.yml`: https://github.com/mnapoli/bref#php-configuration

File uploads would be handled through your framework through PSR-7 but they are not implemented yet (https://github.com/mnapoli/bref/blob/4eaf0e49e16162a6457009dce9de6faa99763af1/src/Bridge/Psr7/RequestFactory.php#L44), so disabling them through php.ini wouldn't affect that. For the rest we use the default `php.ini` settings. If you see a specific issue feel free to mention it.

**Comment by gregmsanderson** [comment]
I see, thank you.

I am new to all this so that clarifies things a bit.

Can _any_ PHP setting be set via that .bref.yml? I saw the documented ones and assumed it was limited to just those ones. If so, I could set them there.

**Comment by mnapoli** [comment]
Indeed you can set any flag, I've pushed a commit to improve the documentation to reflect that.

Thanks for the feedback!
