### ISSUE TITLE
RFC: Session handling when using Symfony framework

### ISSUE THREAD

**Issue by nealio82** [mnapoli/bref#59]
Obviously, with Lambda being totally ephemeral, we need to store sessions in some external data store when performing functions which require storing state between requests (such as logging in to  an admin)

One such way is to use the Symfony `PdoSessionHandler` https://symfony.com/doc/current/doctrine/pdo_session_storage.html

When testing locally using the `php -S 127.0.0.1:8000 bref.php` command, this works fine. However, running in the Lambda environment the session doesn't work.

Although the session appears to be created, for some reason the response object (`$symfonyResponse = $this->httpKernel->handle($symfonyRequest);`) in `/src/Bridge/Symfony/SymfonyAdapter.php` doesn't contain the session cookie / `Set-Cookie` header, and so the client never sends the `PHPSESSID` cookie back on the next request.

Additionally, when using Symfony, the framework has its own interface for accessing the its own internal session handling, meaning you can't use `session_id()` or other `session_...` methods for interacting with the session handling.

Adding the cookie header is easily fixed by adding the following code to `SymfonyAdapter.php`:
```
$symfonyResponse->headers->setCookie(
    new Cookie(
        session_name(),
        $this->httpKernel->getContainer()->get('session')->getId()
    )
);
```
However, during the login cycle, requests are redirected using `301` and `302` redirects, and unless the session id is passed to Symfony, a new session id is generated each time and thus is never re-fetched from the data store. This means that the user record is stored authenticated in the database, but as the client has received a new `PHPSESSID` cookie, the session is never retrieved back from the data store and the user is not able to access the logged-in content. 

This can also be fixed by adding the following to `SymfonyAdapter.php`:
```
if (!is_null($symfonyRequest->cookies->get(session_name()))) {
    $this->httpKernel->getContainer()->get('session')->setId(
        $symfonyRequest->cookies->get(session_name())
    );
}
```

However, this means that in order to work with Symfony's sessions, the `handle` method now looks like this:
```
public function handle(ServerRequestInterface $request): ResponseInterface
{
    $httpFoundationFactory = new HttpFoundationFactory;

    $symfonyRequest = $httpFoundationFactory->createRequest($request);

    if (!is_null($symfonyRequest->cookies->get(session_name()))) {
        $this->httpKernel->getContainer()->get('session')->setId(
            $symfonyRequest->cookies->get(session_name())
        );
    }

    $symfonyResponse = $this->httpKernel->handle($symfonyRequest);

    $symfonyResponse->headers->setCookie(
        new Cookie(
            session_name(),
            $this->httpKernel->getContainer()->get('session')->getId()
        )
    );

    if ($this->httpKernel instanceof TerminableInterface) {
        $this->httpKernel->terminate($symfonyRequest, $symfonyResponse);
    }

    $psr7Factory = new DiactorosFactory;
    $response = $psr7Factory->createResponse($symfonyResponse);

    return $response;
}
```

This looks quite ugly to me, and contains quite a lot of code just to solve a single implementation problem. However, without it, sessions won't work when using Symfony.

Is it better to:
1. include the code by default
1. add to the Symfony-specific documentation in the `mnapoli/bref` repo that when using the `PdoSessionHandler` class, you should extend `SymfonyAdapter` with the session-specific stuff
1. something else?

**Comment by mnapoli** [comment]
Wow that is awesome thanks for all the details.

The Symfony adapter is supposed to take care of the details, so I think we should do that by default (until we have a better solution at least).

This is weird that Symfony does not set the `Set-Cookie` header.

>  the framework has its own interface for accessing the its own internal session handling, meaning you can't use session_id() or other session_... methods for interacting with the session handling.

Is this the root cause from what you've seen? Maybe there an implementation that we can write for this interface that would work better? I haven't digged yet though.

**Comment by nealio82** [comment]
I believe this to be the cause. It appears to make sense that it would be the problem, as other frameworks have been demonstrated to be working with sessions / `bref`

In debugging this I initially wrote a bridge extending the Synmfony `PdoSessionHandler` class and set a constant session id, and returned the same session id from `SymfonyAdapter`. Once I added the lines to set the cookie id above the call to `handle()`, i was able to remove my bridge and the example code above is the minimum required in order to have session support right now.

> This is weird that Symfony does not set the Set-Cookie header.

I agree. I have to wonder if the Symfony session handling requires something from the PHP `$_SESSION` superglobal which isn't available from the compiled php binary supplied with `bref`, or from the CLI environment it is invoked by in order to manage the session fully.

However, I'm not familiar enough with the Symfony session component to fully debug / understand why it's not returned in the response from the `Kernel`.

> The Symfony adapter is supposed to take care of the details, so I think we should do that by default (until we have a better solution at least).

Ok, I can make a PR for this. I was hesitant to do it by default as it's a problem which only shows itself when you want to actually use session storage, rather than something which is needed 100% of the time (although, thinking about it, forms with CSRF protection will also need to use session storage)
