### ISSUE TITLE
Different php versions

### ISSUE THREAD

**Issue by autodeck** [mnapoli/bref#61]
Are there any plans to add other versions of php? i.e. 7.0, 7.1?

If not, how would one go about adding one?

**Comment by t-geindre** [comment]
This is not documented yet but, in a `bref.yml` file, you can provide your own URL to download the PHP archive:
see https://github.com/mnapoli/bref/blob/master/src/Console/Deployer.php#L148

**Comment by mnapoli** [comment]
Note that Bref requires 7.1 (https://github.com/mnapoli/bref/blob/master/composer.json#L17) so we probably won't provide 7.0.

I could add new versions but since this is a bit of work for me I would rather wait to see if there is a lot of demand. @autodeck do you need a specific version?

**Comment by autodeck** [comment]
@t-geindre - Thanks
@mnapoli - We currently need 7.0.21. Can https://github.com/mnapoli/bref/blob/master/bin/php/build.sh be used to build php for bref or are there other requirements/issues with doing that?

**Comment by mnapoli** [comment]
@autodeck yes you can use that script and Dockerfile. Keep in mind that the last line (`aws s3 cp`) uploads to the `bref-php` bucket, that will not work for you. You can remove it or replace it to store your archive in a bucket of yours.

But again I would advise you to test (locally first) if the Bref classes used in the lambda will work with PHP 7.0.

**Comment by mnapoli** [comment]
I'm closing this issue for now to keep the issue tracker organized, we'll reopen in needed.
