### ISSUE TITLE
Unable to use php 7.0

### ISSUE THREAD

**Issue by autodeck** [mnapoli/bref#63]
Following on from issue #61, when using php 7.0, I get the following:

Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/task/vendor/mnapoli/bref/src/Application.php on line 27

**Comment by mnapoli** [comment]
Hi @autodeck, this is not a bug. As explained in #61 Bref supports only PHP 7.1 and up.

PHP 7.0 has not been supported for 9 months and will stop getting security updates in 2 months, so I don't see a strong reason to spend time and effort to support that version (see https://secure.php.net/supported-versions.php).
