### ISSUE TITLE
Using Postgresql Database

### ISSUE THREAD

**Issue by nurwin** [mnapoli/bref#77]
Hi.. I have laravel application that run with pgsql database. is it possible to using it? in aws I will use RDS. how to integrate with it?

Thanks in advice.

**Comment by nurwin** [comment]
yes, when I run it, the apps return "error could not find driver", is bref support pgsql database?

**Comment by nurwin** [comment]
should I modify the dockerfile on vendor?

**Comment by wysow** [comment]
Hum... You're right, we should compile the pgsql driver for php to be used in bref.

**Comment by nurwin** [comment]
@mnapoli would you like to add enhancement for this issue? thank you

**Comment by mnapoli** [comment]
@nurwin I do not need that at the moment so I will not work on that. However feel free to send a pull request to add PostgreSQL support, that would be great!

**Comment by davidavz** [comment]
You just have to add the `--with-pdo-pgsql` into the [Dockerfile](https://github.com/mnapoli/bref/blob/master/bin/php/Dockerfile#L58) isn't it?

**Comment by mnapoli** [comment]
I think so, I have never used it so I'm not 100% sure if it needs other dependencies though.

**Comment by thiagomarini** [comment]
Need to add `RUN yum install postgresql-devel -y` before `--with-pdo-pgsql`

**Comment by thiagomarini** [comment]
I've compiled a binary with MySQL and Postgres if anyone wants:

https://s3-eu-west-1.amazonaws.com/assets.weengs.com/php-7.2.5.tar.gz

Just place it inside `.bref/bin/php` folder that Bref won't overwrite it on deploy

**Comment by mnapoli** [comment]
The PostgreSQL extension is available in v0.3 (see https://bref.sh/docs/environment/php.html to enable it) 🎉

**Comment by nurwin** [comment]
Thanks @mnapoli
