### ISSUE TITLE
Reserved option value for bref:invoke, local execution

### ISSUE THREAD

**Issue by krcrawford** [mnapoli/bref#78]
While running the following:
```php
php bref.php bref:invoke # with or without an event
```
returns:
```shell
In InputDefinition.php line 238:

  [Symfony\Component\Console\Exception\LogicException]
  An option with shortcut "e" already exists.
```

Any ideas what I might be doing wrong? Or is this a bug?

result of:
```shell
vendor/symfony/console/Input/InputDefinition.php:232 -> throw new LogicException(sprintf('An option named "%s" already exists.', $option->getName()));
vendor/symfony/console/Input/InputDefinition.php:222 -> $this->addOption($option);
```

**Comment by mnapoli** [comment]
Hi, have you defined a custom command with a `-e` shortcut in your app?

**Comment by krcrawford** [comment]
nope, only using bref

**Comment by mnapoli** [comment]
Right do you have extra packages installed in `composer.json`? If so please list them. And if you have any command registered please list them with their options. Also please post the complete stack trace, the screenshot is incomplete.

Could you also let us know which version of Bref you are using. If you are not using the latest, please try again with the latest.

Without more info I'm afraid I cannot help.

FYI I tried from scratch:

```
composer require mnapoli/bref
vendor/bin/bref init
php bref.php bref:invoke
```

and it works.

**Comment by mnapoli** [comment]
Closing until we can identify whether it's really a bug.
