### ISSUE TITLE
Unable to read AWS Credentials on Laravel Set up 

### ISSUE THREAD

**Issue by paulkamau2015** [mnapoli/bref#79]
In the serverless laravel Guide on (https://mnapoli.fr/serverless-laravel/), I keep having trouble when running the "vendor/bin/bref init" command. I keep getting this error: 

[ERROR] AWS credentials not found.  
Please follow the instructions on https://github.com/mnapoli/bref#setup

I have tried this: 

serverless config credentials --provider aws --key keyhere --secret secret here 

and also running:

set AWS_ACCESS_KEY_ID=id here
set AWS_SECRET_ACCESS_KEY=secret here

but I still getting the above error. Can you help, please? I'm stuck

**Comment by mnapoli** [comment]
I tried it again from scratch just to make sure but it worked fine on my machine.

Can you try to see if `echo $AWS_ACCESS_KEY_ID` or `aws configure get aws_access_key_id` return a value? One of those should, else there's a problem with the configuration.

Btw are you on Windows?

**Comment by paulkamau2015** [comment]
@mnapoli , 

Thanks for responding. Yes, I am using a windows machine. 

Also, it looks like` "vendor/bin/bref" `init is working now. I restarted my computer and it looks like the problem is gone now! 

Thanks!!!

**Comment by paulkamau2015** [comment]
Also, is there anything special with Windows machines? any recommendations? Thanks!

**Comment by mnapoli** [comment]
Maybe you need to restart the terminal when you define an environment variable 🤷‍♂️

**Comment by paulkamau2015** [comment]
I think that may have been the trick! 👍

**Comment by paulkamau2015** [comment]
One more thing, how can I connect a database to this? For example Aurora? And also, do you have any suggestions for scheduled jobs and how this can run for Laravel while it is serverless? Thanks

**Comment by mnapoli** [comment]
I want to write a tutorial for that but in the meantime you can find some of that on google. You will need to configure that using the serverless framework in `serverless.yml`.

**Comment by paulkamau2015** [comment]
Great. thanks for making this so approachable. Really appreciate it!
