### ISSUE TITLE
Publish Lambda function under different version tags?

### ISSUE THREAD

**Issue by ondrejmirtes** [mnapoli/bref#88]
Hi Matthieu,
my usecase is that I'd like to have a Lambda function to run different PHPStan versions. So ideally I'd like to have the ability to invoke different lambda versions identified by a commit hash. This is possible since the `invoke` API has a `qualifier` field that does exactly this.

But how should I publish lambda function under a specific version qualified with Serverless/Bref?

Thank you.

**Comment by mnapoli** [comment]
Right, I don't know sorry. However if you depend on the lambda's version then that means you can never update your runners right?

Would it make more sense to use "stages" instead? (those can be deployed using the `--stage` option)

**Comment by ondrejmirtes** [comment]
I don't think I have any disadvantage with this approach. I just want to run the same code under different PHPStan versions and compare the results.

**Comment by mnapoli** [comment]
Yes but let's say you want to fix an error in your runner, or update Bref?

Actually I just discovered you can use aliases (like git tags/branches). It seems you need to use a serverless plugin though: https://github.com/HyperBrain/serverless-aws-alias

**Comment by ondrejmirtes** [comment]
Yeah, I'd have to update all the Lambda versions at that point.

I'm not sure whether aliases are the right solution but I will take a look 😊

**Comment by mnapoli** [comment]
:+1: closing this for now.
