### ISSUE TITLE
Bref\Console\Deployer not found

### ISSUE THREAD

**Issue by amp9020** [mnapoli/bref#89]
I can run bref init

but when running brief deploy:

PHP Fatal error:  Uncaught Error: Class 'Bref\Console\Deployer' not found in /home/ubuntu/test/demo/vendor/bin/bref:114

Any clues?

thanks in advance,

**Comment by mnapoli** [comment]
Hi, I'm sorry I have no idea, this is really surprising behavior. Did you install Bref in an empty directory?

Can you check that the class/file exists in the vendor directory?

**Comment by amp9020** [comment]
thanks for replying, i started all over, and created it in a blank dir.
it works. thanks!

a few more questions,  i have a laravel application that can be created using composer,
is it better to:

a) composer create-project myown-laravel-app 
then add cd into the new directory and do:

composer require mnapoli/bref
vendor/bin/bref init

or start blank, get bref working and then try to import the laravel app?

**Comment by mnapoli** [comment]
I would advise starting with a working Laravel app (and follow the documentation about Bref and Laravel). However it's always good to first deploy a simple lambda, without Laravel, just to get it working at first. Having small successes is important! :)
