### ISSUE TITLE
Can't change AWS region, serverless.yml changes are overridden

### ISSUE THREAD

**Issue by mheki** [mnapoli/bref#90]
First of all thanks for great library.
I have two issues.
First one - I can't change AWS region to anything else than `us-east-1`

- aws config shows `eu-west-1`
- I've also exported `AWS_DEFAULT_REGION=eu-west-1`
- finally I tried with changing `.serverless/` files and hardcoding `eu-west-1` where I found `us-east-1` but no luck

I've also tried to add `region: eu-west-1` to serverless.yml file but it's always overridden during deployment.

Here is my other issue:
- WelcomeApplication says:

> If you do not want the application to be accessible through HTTP, simply edit your `serverless.yml` file and deploy again

but when I remove `events` lines, they are brought back during another deployment.

**Comment by mnapoli** [comment]
Hi, `region: eu-west-1` in `serverless.yml` is what you should do, that's what I use (with success).

Have you deployed your lambda in another region? You probably need to delete it first (`bref remove`) and recreate it again.

> but when I remove events lines, they are brought back during another deployment.

Do you mean that `serverless.yml` is modified when Bref runs? 🤔 that's weird. Or wait, are you modifying the `serverless.yml` file in the `.bref/output/` directory? You should not modify things in there, those are generated files.

**Comment by mheki** [comment]
Hi @mnapoli that was actually it - I had wrong `serverless.yml` file open. 
Deployment doesn't read my configured region / region from env vars but since setting it in `serverless.yml` helps that's not an issue but nice to have.
Thanks 👍
