### ISSUE TITLE
Support opcode preloading for PHP 7.4

### ISSUE THREAD

**Issue by staabm** [mnapoli/bref#92]
the [php preloading ref](https://wiki.php.net/rfc/preload) landed in [php-src@master recently](https://github.com/php/php-src/commit/f6d227ed4f5d4c0276eb720806e808baceb37f10).

it might make sense to - at least prototype - how pref can/should work with php-src preloading and how it can/will affect runtime performance.

the feature is rather new and requires a cutting edge php build - but I guess the target audience of Bref also works on pretty recent versions and are curious/willing to use such things / take this risk.

take this is not as a reall feature request but more a kind of start the discussion thing.

thanks

**Comment by mnapoli** [comment]
👍 I was thinking about it this week. I wonder if the opcache file can be useful here. From what I understood preloaded files are not even fetched from opcache so I'm not sure, it might be worth testing. Fortunately we have time until PHP 7.4 ^^

**Comment by staabm** [comment]
I guess we can save the time which currently is spent for autoloading the framework.

**Comment by mnapoli** [comment]
Yes what I mean by "I wonder if the opcache file can be useful here" is about [this option](https://secure.php.net/manual/en/opcache.configuration.php#ini.opcache.file-cache).

**Comment by mnapoli** [comment]
Let's reopen when 7.4 is released, in the meantime having this issue in the todo list is not useful.
