### ISSUE TITLE
Dotenv component missing

### ISSUE THREAD

**Issue by vincentwongso** [mnapoli/bref#93]
Encountered the following error on my cloudwatch after following the symfony's instruction:

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Dotenv" from namespace "Symfony\Component\Dotenv".
Did you forget a "use" statement for another namespace? in /var/task/bref.php:14
Stack trace:
#0 {main}
thrown in /var/task/bref.php on line 14
```

Anyone experiencing the same issue?

**Comment by mnapoli** [comment]
DotEnv is in `require-dev`, so it's not installed in production.

Here is what is in `bref.php` causing the error:

```php
// The check is to ensure we don't use .env in production
if (!isset($_SERVER['APP_ENV'])) {
    (new Dotenv)->load(__DIR__.'/.env');
}
```

So I guess the `APP_ENV` is not defined. Please follow the documentation for Symfony: https://github.com/mnapoli/bref/blob/master/docs/Symfony.md
