### ISSUE TITLE
Assume IAM role in AWS PHP SDK?

### ISSUE THREAD

**Issue by ondrejmirtes** [mnapoli/bref#94]
Hi, how should I assume AWS IAM role in Lambda running with Bref?

I found this documentation article https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_assume_role.html but I'm not sure if it applies here - feels like it should be easier 😊

**Comment by mnapoli** [comment]
For this you can have a look at the serverless.com documentation: https://serverless.com/framework/docs/providers/aws/guide/iam/ Internally Bref uses that framework, so you can do everything that you can do with it using `serverless.yml`.

**Comment by ondrejmirtes** [comment]
I know but I worry that AWS PHP SDK will read try reading the access key and secret from somewhere and will not find it there, therefore not letting me query other AWS services.

**Comment by mnapoli** [comment]
I don't understand you question 🤔

**Comment by ondrejmirtes** [comment]
JavaScript AWS SDK has this capability: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-lambda.html

There's no capability like this in PHP AWS SDK, at least it's not in the documentation.

**Comment by mnapoli** [comment]
🤔 	have you tried? It should work. AWS defines the access keys in environment variables, those are picked up by the PHP AWS SDK.

The access keys are bearing the role that was assigned to the lambda.

**Comment by ondrejmirtes** [comment]
Yeah, of course it works, I should have checked first :( I thought that AWS JS SDK contains some "magic sauce" and since AWS does not officially support running PHP in Lambda, it wouldn't be possible. Sorry!

**Comment by mnapoli** [comment]
No worries :)

All of this definitely needs more documentation!
