### ISSUE TITLE
Request for extension `bcmath`

### ISSUE THREAD

**Issue by oppiansteve** [mnapoli/bref#95]
This is needed for (some?) watchers in Laravel Telescope. (At least the `EventWatcher`).

Still working on getting Telescope usable, so not an urgent request as may not be possible anyway (or at least not for the watchers that need it).

I'm mostly getting Telescope working as a reasonably complex app (along with Nova) to see where the pain points are with Bref.

**Comment by oppiansteve** [comment]
It looks like I just need to add the flag `--enable-bcmath` then do the same for the extension `bcmath` as you do for `intl`. (And update the README.md).

I'll just duplicate the extension build script segment of instructions for now, as I'm not sure of the most efficient way to do the same `RUN` commands but over a list of different `WORKDIR`s (without killing the layer caching?). (Bit new to this).  Unless you have a better way to do that.

Just testing this now (over very slow wifi in a Starbucks in Hamburg).

**Comment by mnapoli** [comment]
We defined a list of pre-installed extensions for v0.3 (see https://bref.sh/docs/environment/php.html), bcmath isn't built by default.

If you want to use it you will have to compile it yourself in your lambda and enable it with a `php.ini` (https://bref.sh/docs/environment/php.html should explain a bit more).

I'll close this issue for now.
